### ISSUE TITLE
文字列による駒移動

### ISSUE THREAD

**Issue by cive** [cive/Shogi_alpha#11]
文字列を受け取り、駒を移動するメソッドをGameBoardに実装
ex) 7776 -> 7七にいる駒を7六に移動
ex) 8822+ -> 8八にいる駒を2二に移動し、かつ成る
ex) 金52 -> 持ち駒から5二に金を指す
SFEN(Shogi Forsyth-Edwards Notation)を少し変化させたもの

**Comment by fermiumbay** [comment]
駒の略字は 歩, 香, 桂, 銀, 金, 角, 飛 でオッケーですか？

**Comment by cive** [comment]
大丈夫です。成駒はそれぞれ成香、成桂などもありますが、
成香：杏
成桂：圭
成銀：全
馬
竜
と対応していただけると助かります。
https://ja.wikipedia.org/wiki/%E5%B0%86%E6%A3%8B#.E9.A7.92.E3.81.AE.E5.8B.95.E3.81.8D
